--Tarea para crea
--2.3. Ejercicio 1: Definición de Datos (Actividad Grupal)

ESPECTACULOS (COD_ESPECTACULO, NOMBRE, TIPO, FECHA_INICIAL,
FECHA_FINAL, INTERPRETE, COD_RECINTO)

PRECIOS_ESPECTACULOS (COD_ESPECTACULO, COD_RECINTO, ZONA,
PRECIO)

RECINTOS (COD_RECINTO, NOMBRE, DIRECCION, CIUDAD, TELEFONO,
HORARIO)

ZONAS_RECINTOS (COD_RECINTO, ZONA, CAPACIDAD)
ASIENTOS (COD_RECINTO, ZONA, FILA, NUMERO)

REPRESENTACIONES (COD_ESPECTACULO, FECHA, HORA)

ENTRADAS (COD_ESPECTACULO, FECHA, HORA, COD_RECINTO, FILA,
NUMERO, ZONA, DNI_CLIENTE)

ESPECTADORES (DNI_CLIENTE, NOMBRE, DIRECCION, TELEFONO, CIUDAD,
NTARJETA)

stablecer las claves primarias de cada una de las tablas

CREATE TABLE personas.dbo.city (
    id int  NOT NULL IDENTITY(1, 1),
    city_name char(128)  NOT NULL,
    lat decimal(9,6)  NOT NULL,
    long decimal(9,6)  NOT NULL,
    country_id int  NOT NULL,
    CONSTRAINT city_pk PRIMARY KEY  (id)
);
